server:
  port: 7070

spring:
  application:
    name: schedule
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  provider:
    filter: -exception
    version: 1.0.0
  scan:
    base-packages: org.example.webservice.provider, org.example.webservice.service
  consumer:
    version: 1.0.0
    check: false
    timeout: 10000
#  Mybatis
mybatis:
  typeAliasesPackage: org.example.commonservice.core.entity
  mapperLocations: classpath*:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#  logback
logging:
  file:
    name: logs
