server:
  port: 7070

spring:
  application:
    name: schedule
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  provider:
    filter: remoteServiceException,-exception
    version: 1.0.0
  consumer:
    version: 1.0.0
    check: false
    timeout: 10000
#  Mybatis
mybatis:
  typeAliasesPackage: org.example.**.mapper
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
#  logback
logging:
  file:
    name: logs
