server:
  port: 7070

spring:
  application:
    name: schedule
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
#  Mybatis
mybatis:
  typeAliasesPackage: org.example.**.mapper
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
#  logback
logging:
  file:
    name: logs
