server:
  port: 1001
  netty:
    connection-timeout: 250ms
    max-initial-line-length: 16KB
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER:http://127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:book-review}
        prefix: ${spring.application.name}
        group: ${GROUP:book}
        enabled: true
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin
          uri: lb://api
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: front
          uri: lb://api
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
            - ForwardHeaders=Authorization
        - id: auth
          uri: lb://api
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - PUT
              - DELETE
              - PATCH
              - POST
      default-filters:
        - RemoveRequestHeader=Host
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: DEBUG