server:
  port: 1001
  netty:
    connection-timeout: 250ms
    max-initial-line-length: 16KB
spring:
  application:
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        prefix: ${spring.application.name}
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      discovery:
        register-enabled: true
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin
          uri: lb://api
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: front
          uri: lb://api
          predicates:
            - Path=/front/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://api
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - PUT
              - DELETE
              - PATCH
              - POST
      default-filters:
        - RemoveRequestHeader=Host
# configuration dubbo with other services
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  provider:
    filter: remoteServiceException,-exception
    version: 1.0.0
  consumer:
    version: 1.0.0
    check: false
    timeout: 10000
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: DEBUG