server:
  port: 7060
  forward-headers-strategy: framework
spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:book-review}?&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:nacos123}
    hikari:
      connectionTimeout: 60000
      initializationFailTimeout: 3000
      connectionTestQuery: SELECT 1
      validationTimeout: 60000
      maxLifetime: 35000
      maximumPoolSize: 50
      minimumIdle: 10
      idleTimeout: 30000
      registerMbeans: false
      poolName: bookReview
      isolate-internal-queries: true

# service for registry
  cloud:
    nacos:
      config:
        enabled: true
      discovery:
        server-addr: ${NACOS_SERVER:http://127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:book-review}
        group: ${GROUP:book}
        enabled: true

# configuration dubbo with other services
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?namespace=book-review
    timeout: 5000
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=book-review
    timeout: 5000
  enabled: false

#  api document
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /documents
    default-models-expand-depth: -1

#  logback
logging:
  file:
    name: logs
  level:
    org:
      springframework:
        data:
          redis:
            core:
              RedisTemplate: INFO


