server:
  port: 7060
  forward-headers-strategy: framework
spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:book-review}?&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:nacos123}
    hikari:
      connectionTimeout: 60000
      initializationFailTimeout: 3000
      connectionTestQuery: SELECT 1
      validationTimeout: 60000
      maxLifetime: 35000
      maximumPoolSize: 50
      minimumIdle: 10
      idleTimeout: 30000
      registerMbeans: false
      poolName: bookReview
      isolate-internal-queries: true
# service for registry
  cloud:
    nacos:
      config:
        enabled: true
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: public
        group: DEFAULT_GROUP
        register-enabled: true
        username: nacos
        password: nacos
# configuration dubbo with other services
dubbo:
  application:
    name: api
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=public
    timeout: 5000
    username: nacos
    password: nacos
  provider:
    filter: remoteServiceExceptionFilter,-exception
    version: 1.0.0
    register: false
  consumer:
    version: 1.0.0
    timeout: 10000
    check: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /documents
    default-models-expand-depth: -1
# logback
logging:
  file:
    name: logs
  level:
    org:
      springframework:
        data:
          redis:
            core:
              RedisTemplate: INFO


