server:
  port: 7060

spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    show-sql: false
    open-in-view: false
  jackson:
    time-zone: UTC
# service for registry
  config:
    import: optional:nacos:${spring.application.name}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: book-review
        group: book
        enabled: true
        register-enabled: true
# configuration dubbo with other services
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?namespace=book-review
    timeout: 5000
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=book-review
    timeout: 5000
  enabled: false
#  logback
logging:
  file:
    name: logs
  level:
    org:
      springframework:
        data:
          redis:
            core:
              RedisTemplate: INFO


