server:
  port: 7080
spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:book-review}?&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:nacos123}
    hikari:
      connectionTimeout: 60000
      initializationFailTimeout: 3000
      connectionTestQuery: SELECT 1
      validationTimeout: 60000
      maxLifetime: 35000
      maximumPoolSize: 50
      minimumIdle: 10
      idleTimeout: 30000
      registerMbeans: false
      poolName: bookReview
      isolate-internal-queries: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    show-sql: false
    open-in-view: false
  jackson:
    time-zone: UTC

  # service for registry
  cloud:
    nacos:
      config:
        enabled: true
      discovery:
        server-addr: ${NACOS_SERVER:http://127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:book-review}
        group: ${GROUP:book}
        enabled: true

  # redis tools
  data:
    redis:
      port: 6379
      username: nacos
      password: libra123
      database: 0
      timeout: 10ms
      lettuce:
        pool:
          max-wait: -1ms
          max-idle: 10
          max-active: 10
          min-idle: 0
# configuration dubbo with other services
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?namespace=book-review
    timeout: 5000
  metadata-report:
    address: nacos://127.0.0.1:8848?namespace=book-review
    timeout: 5000
  enabled: false
#  Mybatis
mybatis:
  typeAliasesPackage: org.example.**.core.entity
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
#  logback
logging:
  file:
    name: logs
  level:
    org:
      springframework:
        data:
          redis:
            core:
              RedisTemplate: INFO